'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace UomSvc
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="UomSvc.IUomService")>  _
    Public Interface IUomService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IUomService/UomAdd", ReplyAction:="http://tempuri.org/IUomService/UomAddResponse")>  _
        Function UomAdd(ByVal uom As ProductSvr.Model.Uom) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IUomService/UomModify", ReplyAction:="http://tempuri.org/IUomService/UomModifyResponse")>  _
        Function UomModify(ByVal uom As ProductSvr.Model.Uom, ByVal uom_code As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IUomService/UomDelete", ReplyAction:="http://tempuri.org/IUomService/UomDeleteResponse")>  _
        Function UomDelete(ByVal uom_code As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IUomService/GetUom", ReplyAction:="http://tempuri.org/IUomService/GetUomResponse")>  _
        Function GetUom() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IUomService/RecordUom", ReplyAction:="http://tempuri.org/IUomService/RecordUomResponse")>  _
        Function RecordUom(ByVal uom_code As String) As ProductSvr.Model.Uom
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IUomServiceChannel
        Inherits UomSvc.IUomService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class UomServiceClient
        Inherits System.ServiceModel.ClientBase(Of UomSvc.IUomService)
        Implements UomSvc.IUomService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function UomAdd(ByVal uom As ProductSvr.Model.Uom) As String Implements UomSvc.IUomService.UomAdd
            Return MyBase.Channel.UomAdd(uom)
        End Function
        
        Public Function UomModify(ByVal uom As ProductSvr.Model.Uom, ByVal uom_code As String) As String Implements UomSvc.IUomService.UomModify
            Return MyBase.Channel.UomModify(uom, uom_code)
        End Function
        
        Public Function UomDelete(ByVal uom_code As String) As String Implements UomSvc.IUomService.UomDelete
            Return MyBase.Channel.UomDelete(uom_code)
        End Function
        
        Public Function GetUom() As System.Data.DataTable Implements UomSvc.IUomService.GetUom
            Return MyBase.Channel.GetUom
        End Function
        
        Public Function RecordUom(ByVal uom_code As String) As ProductSvr.Model.Uom Implements UomSvc.IUomService.RecordUom
            Return MyBase.Channel.RecordUom(uom_code)
        End Function
    End Class
End Namespace
