'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace DeliverSvc
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="DeliverSvc.IDeliverService")>  _
    Public Interface IDeliverService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDeliverService/DeliverAdd", ReplyAction:="http://tempuri.org/IDeliverService/DeliverAddResponse")>  _
        Function DeliverAdd(ByVal dl As ProductSvr.Model.Deliver, ByVal dlp() As ProductSvr.Model.DeliverProduct) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDeliverService/GetDeliver", ReplyAction:="http://tempuri.org/IDeliverService/GetDeliverResponse")>  _
        Function GetDeliver() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDeliverService/GetDeliverReport", ReplyAction:="http://tempuri.org/IDeliverService/GetDeliverReportResponse")>  _
        Function GetDeliverReport(ByVal a As Date, ByVal b As Date) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDeliverService/GetDeliverProduct", ReplyAction:="http://tempuri.org/IDeliverService/GetDeliverProductResponse")>  _
        Function GetDeliverProduct(ByVal id As Integer) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDeliverService/DeliveryDelete", ReplyAction:="http://tempuri.org/IDeliverService/DeliveryDeleteResponse")>  _
        Function DeliveryDelete(ByVal id As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IDeliverService/DeliveryRecord", ReplyAction:="http://tempuri.org/IDeliverService/DeliveryRecordResponse")>  _
        Function DeliveryRecord(ByVal id As Integer) As ProductSvr.Model.Deliver
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IDeliverServiceChannel
        Inherits DeliverSvc.IDeliverService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class DeliverServiceClient
        Inherits System.ServiceModel.ClientBase(Of DeliverSvc.IDeliverService)
        Implements DeliverSvc.IDeliverService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function DeliverAdd(ByVal dl As ProductSvr.Model.Deliver, ByVal dlp() As ProductSvr.Model.DeliverProduct) As String Implements DeliverSvc.IDeliverService.DeliverAdd
            Return MyBase.Channel.DeliverAdd(dl, dlp)
        End Function
        
        Public Function GetDeliver() As System.Data.DataTable Implements DeliverSvc.IDeliverService.GetDeliver
            Return MyBase.Channel.GetDeliver
        End Function
        
        Public Function GetDeliverReport(ByVal a As Date, ByVal b As Date) As System.Data.DataTable Implements DeliverSvc.IDeliverService.GetDeliverReport
            Return MyBase.Channel.GetDeliverReport(a, b)
        End Function
        
        Public Function GetDeliverProduct(ByVal id As Integer) As System.Data.DataTable Implements DeliverSvc.IDeliverService.GetDeliverProduct
            Return MyBase.Channel.GetDeliverProduct(id)
        End Function
        
        Public Function DeliveryDelete(ByVal id As Integer) As String Implements DeliverSvc.IDeliverService.DeliveryDelete
            Return MyBase.Channel.DeliveryDelete(id)
        End Function
        
        Public Function DeliveryRecord(ByVal id As Integer) As ProductSvr.Model.Deliver Implements DeliverSvc.IDeliverService.DeliveryRecord
            Return MyBase.Channel.DeliveryRecord(id)
        End Function
    End Class
End Namespace
