'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace OrderSvc
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="OrderSvc.IOrderService")>  _
    Public Interface IOrderService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOrderService/OrderAdd", ReplyAction:="http://tempuri.org/IOrderService/OrderAddResponse")>  _
        Function OrderAdd(ByVal [or] As ProductSvr.Model.Order, ByVal orp() As ProductSvr.Model.OrderProduct) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOrderService/OrderModify", ReplyAction:="http://tempuri.org/IOrderService/OrderModifyResponse")>  _
        Function OrderModify(ByVal [or] As ProductSvr.Model.Order, ByVal orp() As ProductSvr.Model.OrderProduct) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOrderService/GetOrder", ReplyAction:="http://tempuri.org/IOrderService/GetOrderResponse")>  _
        Function GetOrder() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOrderService/GetOrderReport", ReplyAction:="http://tempuri.org/IOrderService/GetOrderReportResponse")>  _
        Function GetOrderReport(ByVal d_a As Date, ByVal dz As Date) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOrderService/GetOrderProduct", ReplyAction:="http://tempuri.org/IOrderService/GetOrderProductResponse")>  _
        Function GetOrderProduct(ByVal id As Integer) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOrderService/OrderDelete", ReplyAction:="http://tempuri.org/IOrderService/OrderDeleteResponse")>  _
        Function OrderDelete(ByVal id As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IOrderService/OrderRecord", ReplyAction:="http://tempuri.org/IOrderService/OrderRecordResponse")>  _
        Function OrderRecord(ByVal id As Integer) As ProductSvr.Model.Order
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IOrderServiceChannel
        Inherits OrderSvc.IOrderService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class OrderServiceClient
        Inherits System.ServiceModel.ClientBase(Of OrderSvc.IOrderService)
        Implements OrderSvc.IOrderService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function OrderAdd(ByVal [or] As ProductSvr.Model.Order, ByVal orp() As ProductSvr.Model.OrderProduct) As String Implements OrderSvc.IOrderService.OrderAdd
            Return MyBase.Channel.OrderAdd([or], orp)
        End Function
        
        Public Function OrderModify(ByVal [or] As ProductSvr.Model.Order, ByVal orp() As ProductSvr.Model.OrderProduct) As String Implements OrderSvc.IOrderService.OrderModify
            Return MyBase.Channel.OrderModify([or], orp)
        End Function
        
        Public Function GetOrder() As System.Data.DataTable Implements OrderSvc.IOrderService.GetOrder
            Return MyBase.Channel.GetOrder
        End Function
        
        Public Function GetOrderReport(ByVal d_a As Date, ByVal dz As Date) As System.Data.DataTable Implements OrderSvc.IOrderService.GetOrderReport
            Return MyBase.Channel.GetOrderReport(d_a, dz)
        End Function
        
        Public Function GetOrderProduct(ByVal id As Integer) As System.Data.DataTable Implements OrderSvc.IOrderService.GetOrderProduct
            Return MyBase.Channel.GetOrderProduct(id)
        End Function
        
        Public Function OrderDelete(ByVal id As Integer) As String Implements OrderSvc.IOrderService.OrderDelete
            Return MyBase.Channel.OrderDelete(id)
        End Function
        
        Public Function OrderRecord(ByVal id As Integer) As ProductSvr.Model.Order Implements OrderSvc.IOrderService.OrderRecord
            Return MyBase.Channel.OrderRecord(id)
        End Function
    End Class
End Namespace
