'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ProductSvc
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ProductSvc.IProductService")>  _
    Public Interface IProductService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IProductService/ProductAdd", ReplyAction:="http://tempuri.org/IProductService/ProductAddResponse")>  _
        Function ProductAdd(ByVal rm As ProductSvr.Model.Product, ByVal uom As ProductSvr.Model.Uom) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IProductService/ProductModify", ReplyAction:="http://tempuri.org/IProductService/ProductModifyResponse")>  _
        Function ProductModify(ByVal rm As ProductSvr.Model.Product, ByVal uom As ProductSvr.Model.Uom, ByVal key As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IProductService/GetProduct", ReplyAction:="http://tempuri.org/IProductService/GetProductResponse")>  _
        Function GetProduct() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IProductService/recordProduct", ReplyAction:="http://tempuri.org/IProductService/recordProductResponse")>  _
        Function recordProduct(ByVal prodId As String) As ProductSvr.Model.Product
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IProductService/ProductDelete", ReplyAction:="http://tempuri.org/IProductService/ProductDeleteResponse")>  _
        Function ProductDelete(ByVal id As String) As String
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IProductServiceChannel
        Inherits ProductSvc.IProductService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ProductServiceClient
        Inherits System.ServiceModel.ClientBase(Of ProductSvc.IProductService)
        Implements ProductSvc.IProductService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ProductAdd(ByVal rm As ProductSvr.Model.Product, ByVal uom As ProductSvr.Model.Uom) As String Implements ProductSvc.IProductService.ProductAdd
            Return MyBase.Channel.ProductAdd(rm, uom)
        End Function
        
        Public Function ProductModify(ByVal rm As ProductSvr.Model.Product, ByVal uom As ProductSvr.Model.Uom, ByVal key As String) As String Implements ProductSvc.IProductService.ProductModify
            Return MyBase.Channel.ProductModify(rm, uom, key)
        End Function
        
        Public Function GetProduct() As System.Data.DataTable Implements ProductSvc.IProductService.GetProduct
            Return MyBase.Channel.GetProduct
        End Function
        
        Public Function recordProduct(ByVal prodId As String) As ProductSvr.Model.Product Implements ProductSvc.IProductService.recordProduct
            Return MyBase.Channel.recordProduct(prodId)
        End Function
        
        Public Function ProductDelete(ByVal id As String) As String Implements ProductSvc.IProductService.ProductDelete
            Return MyBase.Channel.ProductDelete(id)
        End Function
    End Class
End Namespace
